export * from './producto/producto.component'
export * from './producto-detail/producto-detail.component'
export * from './cliente/cliente.component'
export * from './cliente-detail/cliente-detail.component'
export * from './cliente-producto/cliente-producto.component'
export * from './cliente-producto-detail/cliente-producto-detail.component'
export * from './carritos/carritos.component'